import json
import shutil
import subprocess
from pathlib import Path

import pytest

BUILD_PY = Path(__file__).resolve().parent.parent / "build.py"


@pytest.fixture
def project(tmp_path):
    """A temp dir with its own build.py, so ROOT (= build.py's own dirname)
    resolves inside it and every generated path stays isolated from the
    real repo."""
    shutil.copy2(BUILD_PY, tmp_path / "build.py")
    return tmp_path


def write_bundles(project: Path, yaml_text: str) -> None:
    (project / "bundles.yaml").write_text(yaml_text)


def run_build(project: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [str(project / "build.py"), *args],
        cwd=project,
        capture_output=True,
        text=True,
    )


def test_null_env_value_is_required_and_undescribed_in_catalog(project):
    write_bundles(
        project,
        """
marketplace:
  name: test
  owner: { name: tester }
plugins:
  - name: alpha
    catalog: true
    mcp:
      - name: svc
        command: docker
        env:
          FOO_KEY: null
""",
    )
    result = run_build(project)
    assert result.returncode == 0, result.stderr
    catalog = json.loads((project / "plugins/alpha/.claude-plugin/catalog.json").read_text())
    assert catalog == [
        {"name": "svc", "type": "mcp", "env": [{"name": "FOO_KEY", "required": True, "description": None}]}
    ]


def test_env_metadata_reaches_catalog_json(project):
    write_bundles(
        project,
        """
marketplace:
  name: test
  owner: { name: tester }
plugins:
  - name: alpha
    catalog: true
    mcp:
      - name: svc
        command: docker
        env:
          ZOTERO_API_KEY: { required: false, description: "Zotero Web API key" }
""",
    )
    result = run_build(project)
    assert result.returncode == 0, result.stderr
    catalog = json.loads((project / "plugins/alpha/.claude-plugin/catalog.json").read_text())
    assert catalog[0]["env"] == [
        {"name": "ZOTERO_API_KEY", "required": False, "description": "Zotero Web API key"}
    ]


def test_env_example_annotates_description_and_optional(project):
    write_bundles(
        project,
        """
marketplace:
  name: test
  owner: { name: tester }
plugins:
  - name: alpha
    mcp:
      - name: svc
        command: docker
        env:
          REQUIRED_KEY: null
          ZOTERO_API_KEY: { required: false, description: "Zotero Web API key" }
          OPTIONAL_NO_DESC: { required: false }
""",
    )
    result = run_build(project)
    assert result.returncode == 0, result.stderr
    content = (project / "plugins/alpha/.env.example").read_text()
    assert content == (
        "# Environment variables for the alpha plugin's MCP servers.\n"
        "# Generated by build.py — copy to .env and fill in values.\n"
        "\n"
        "REQUIRED_KEY=\n"
        "# Zotero Web API key (optional)\n"
        "ZOTERO_API_KEY=\n"
        "# (optional)\n"
        "OPTIONAL_NO_DESC=\n"
    )


def test_duplicate_env_var_across_plugins_fails_build(project):
    write_bundles(
        project,
        """
marketplace:
  name: test
  owner: { name: tester }
plugins:
  - name: alpha
    mcp:
      - name: svc
        command: docker
        env:
          SHARED_KEY: null
  - name: beta
    env:
      SHARED_KEY: null
""",
    )
    result = run_build(project)
    assert result.returncode != 0
    assert "SHARED_KEY" in result.stdout
    assert "alpha" in result.stdout
    assert "beta" in result.stdout


def test_duplicate_check_runs_on_scoped_plugin_build(project):
    write_bundles(
        project,
        """
marketplace:
  name: test
  owner: { name: tester }
plugins:
  - name: alpha
    mcp:
      - name: svc
        command: docker
        env:
          SHARED_KEY: null
  - name: beta
    env:
      SHARED_KEY: null
""",
    )
    result = run_build(project, "--plugin", "alpha")
    assert result.returncode != 0
    assert "SHARED_KEY" in result.stdout
    assert "alpha" in result.stdout
    assert "beta" in result.stdout


def test_same_var_within_one_plugin_is_not_a_duplicate(project):
    write_bundles(
        project,
        """
marketplace:
  name: test
  owner: { name: tester }
plugins:
  - name: alpha
    mcp:
      - name: svc-a
        command: docker
        env:
          DB_URI: null
      - name: svc-b
        command: docker
        env:
          DB_URI: null
""",
    )
    result = run_build(project)
    assert result.returncode == 0, result.stderr
